env_name: 'MineRLNavigateDense-v0'
gamma: 0.98
lr: 0.0005
weight_decay: 0.98
lambda_: 0.95
eps_clip: 0.1
k_epochs: 3
max_epi: 1000
agent_num: 1
num_gpus: 0.4
num_channels: 4
num_actions: 6
buffer_limit: 50000
L1: 0.9
pretrain_epochs: 100
threshold: 100
batch_size: 32
seq_len: 10
model_path: /weigths/
T_horizon: 20
